/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cdd493bfb4e5d0ffd528a735f730b113)
interface __BaseEnv_Env {
	LIBRARY_BUCKET: R2Bucket;
	R2_PREFIX: "pdfs/";
	R2_PUBLIC_BASE_URL: "https://assets.sacrumflorilegium.com/";
	PDFJS_BASE_URL: "https://reader.sacrumflorilegium.com/";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PREFIX" | "R2_PUBLIC_BASE_URL" | "PDFJS_BASE_URL">> {}
}
