/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d33c9dcd90c97d02f99471cd93164275)
interface __BaseEnv_Env {
	LIBRARY_BUCKET: R2Bucket;
	R2_PREFIX: "pdfs/";
	R2_PUBLIC_BASE_URL: "https://assets.sacrumflorilegium.com/";
	PDFJS_BASE_URL: "https://reader.sacrumflorilegium.com/web/viewer.html";
	AIRTABLE_BASE_ID: "appEBrDjSYL5WYWft";
	AIRTABLE_BOOKS_TABLE: "Books";
	AIRTABLE_AUTHORS_TABLE: "Authors";
	AIRTABLE_CLASSIFICATIONS_TABLE: "Classifications";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PREFIX" | "R2_PUBLIC_BASE_URL" | "PDFJS_BASE_URL" | "AIRTABLE_BASE_ID" | "AIRTABLE_BOOKS_TABLE" | "AIRTABLE_AUTHORS_TABLE" | "AIRTABLE_CLASSIFICATIONS_TABLE">> {}
}
